name = "WebUtils"
uuid = "4854a8e4-1362-4181-b485-9fa160da65ab"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a" # stdlib

[compat]
julia = "1"

[extras]
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Jive"]
